services:
    bun:
        image: oven/bun:1.2.8
        entrypoint: /bin/bash
        tty: true
        working_dir: /app
        volumes:
            - .:/app
        depends_on:
            - postgres

    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=mikrobun
            - POSTGRES_PASSWORD=mikrobun
            - POSTGRES_DB=mikrobun
        expose:
            - "5432"
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 2s
            timeout: 5s
            retries: 10
